<?php

namespace Database\Seeders;

use App\Models\Supplier;
use App\Models\SupplierProduct;
use App\Constants\DropshipProductSyncStatuses;
use Illuminate\Database\Seeder;

class SupplierProductSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = Supplier::all();

        foreach ($suppliers as $supplier) {
            $this->createProductsForSupplier($supplier);
        }
    }

    private function createProductsForSupplier(Supplier $supplier): void
    {
        $products = $this->getProductsForSupplier($supplier->name);

        foreach ($products as $productData) {
            SupplierProduct::create(array_merge($productData, [
                'supplier_id' => $supplier->id,
                'last_synced_at' => now()->subMinutes(rand(1, 1440)),
            ]));
        }
    }

    private function getProductsForSupplier(string $supplierName): array
    {
        return match($supplierName) {
            'GlobalTech Distributors' => [
                [
                    'supplier_sku' => 'GT-WH-001',
                    'supplier_product_id' => 'GT001',
                    'name' => 'Wireless Bluetooth Headphones Pro',
                    'description' => 'Premium noise-cancelling wireless headphones with 30-hour battery life',
                    'supplier_price' => 4500,
                    'retail_price' => 7999,
                    'stock_quantity' => 150,
                    'weight' => 0.35,
                    'length' => 20.0,
                    'width' => 18.0,
                    'height' => 8.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['headphones-1.jpg', 'headphones-2.jpg'],
                    'attributes' => ['color' => 'Black', 'connectivity' => 'Bluetooth 5.0'],
                    'categories' => ['Electronics', 'Audio'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 2,
                ],
                [
                    'supplier_sku' => 'GT-SP-002',
                    'supplier_product_id' => 'GT002',
                    'name' => 'Smart Phone Stand Adjustable',
                    'description' => 'Universal adjustable phone stand for desk and table use',
                    'supplier_price' => 899,
                    'retail_price' => 1599,
                    'stock_quantity' => 300,
                    'weight' => 0.25,
                    'length' => 12.0,
                    'width' => 10.0,
                    'height' => 15.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['phone-stand-1.jpg'],
                    'attributes' => ['material' => 'Aluminum', 'adjustable' => 'Yes'],
                    'categories' => ['Electronics', 'Accessories'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 2,
                ],
                [
                    'supplier_sku' => 'GT-TC-003',
                    'supplier_product_id' => 'GT003',
                    'name' => 'USB-C Fast Charging Cable 2m',
                    'description' => 'High-speed USB-C to USB-A charging cable with braided design',
                    'supplier_price' => 299,
                    'retail_price' => 899,
                    'stock_quantity' => 500,
                    'weight' => 0.08,
                    'length' => 5.0,
                    'width' => 3.0,
                    'height' => 1.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['usb-cable-1.jpg'],
                    'attributes' => ['length' => '2m', 'type' => 'USB-C to USB-A'],
                    'categories' => ['Electronics', 'Cables'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 1,
                ],
            ],
            'Fashion Forward Wholesale' => [
                [
                    'supplier_sku' => 'FFW-TS-101',
                    'supplier_product_id' => 'FFW101',
                    'name' => 'Premium Cotton T-Shirt Unisex',
                    'description' => 'High-quality 100% organic cotton t-shirt in various colors',
                    'supplier_price' => 1200,
                    'retail_price' => 2499,
                    'stock_quantity' => 200,
                    'weight' => 0.15,
                    'length' => 30.0,
                    'width' => 25.0,
                    'height' => 2.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['tshirt-white.jpg', 'tshirt-black.jpg', 'tshirt-navy.jpg'],
                    'attributes' => ['material' => '100% Organic Cotton', 'sizes' => 'XS-XXL'],
                    'categories' => ['Fashion', 'Clothing', 'T-Shirts'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 3,
                ],
                [
                    'supplier_sku' => 'FFW-JN-102',
                    'supplier_product_id' => 'FFW102',
                    'name' => 'Slim Fit Denim Jeans',
                    'description' => 'Classic slim fit denim jeans with stretch comfort',
                    'supplier_price' => 2500,
                    'retail_price' => 4999,
                    'stock_quantity' => 120,
                    'weight' => 0.65,
                    'length' => 35.0,
                    'width' => 30.0,
                    'height' => 5.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['jeans-blue.jpg', 'jeans-black.jpg'],
                    'attributes' => ['fit' => 'Slim', 'material' => 'Denim with 2% Elastane'],
                    'categories' => ['Fashion', 'Clothing', 'Jeans'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 3,
                ],
            ],
            'HomeDecor Direct' => [
                [
                    'supplier_sku' => 'HDD-CV-201',
                    'supplier_product_id' => 'HDD201',
                    'name' => 'Decorative Canvas Wall Art Set',
                    'description' => 'Modern abstract canvas wall art set of 3 pieces',
                    'supplier_price' => 3500,
                    'retail_price' => 7999,
                    'stock_quantity' => 45,
                    'weight' => 1.2,
                    'length' => 60.0,
                    'width' => 40.0,
                    'height' => 3.0,
                    'sync_status' => DropshipProductSyncStatuses::OUT_OF_SYNC,
                    'images' => ['canvas-art-set.jpg'],
                    'attributes' => ['pieces' => '3', 'style' => 'Modern Abstract'],
                    'categories' => ['Home Decor', 'Wall Art'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 5,
                ],
                [
                    'supplier_sku' => 'HDD-LMP-202',
                    'supplier_product_id' => 'HDD202',
                    'name' => 'Modern Table Lamp with USB Charging',
                    'description' => 'Contemporary table lamp with built-in USB charging ports',
                    'supplier_price' => 4999,
                    'retail_price' => 9999,
                    'stock_quantity' => 25,
                    'weight' => 2.1,
                    'length' => 25.0,
                    'width' => 25.0,
                    'height' => 45.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['table-lamp.jpg'],
                    'attributes' => ['power' => '40W LED', 'features' => 'USB Charging'],
                    'categories' => ['Home Decor', 'Lighting'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 5,
                ],
            ],
            'Asian Marketplace Hub' => [
                [
                    'supplier_sku' => 'AMH-KB-301',
                    'supplier_product_id' => 'AMH301',
                    'name' => 'Bamboo Kitchen Utensil Set',
                    'description' => 'Eco-friendly bamboo kitchen utensils set of 6 pieces',
                    'supplier_price' => 1599,
                    'retail_price' => 2999,
                    'stock_quantity' => 180,
                    'weight' => 0.45,
                    'length' => 35.0,
                    'width' => 10.0,
                    'height' => 3.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['bamboo-utensils.jpg'],
                    'attributes' => ['material' => 'Bamboo', 'pieces' => '6'],
                    'categories' => ['Kitchen', 'Utensils', 'Eco-Friendly'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 7,
                ],
                [
                    'supplier_sku' => 'AMH-TE-302',
                    'supplier_product_id' => 'AMH302',
                    'name' => 'Premium Green Tea Selection Box',
                    'description' => 'Assorted premium green tea collection from various regions',
                    'supplier_price' => 2200,
                    'retail_price' => 3999,
                    'stock_quantity' => 90,
                    'weight' => 0.3,
                    'length' => 25.0,
                    'width' => 15.0,
                    'height' => 8.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['green-tea-box.jpg'],
                    'attributes' => ['varieties' => '8', 'origin' => 'Multiple Asian Regions'],
                    'categories' => ['Food & Beverage', 'Tea'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 7,
                ],
            ],
            'TechGadgets Pro' => [
                [
                    'supplier_sku' => 'TGP-WC-401',
                    'supplier_product_id' => 'TGP401',
                    'name' => 'Wireless Charging Pad 15W',
                    'description' => 'Fast wireless charging pad compatible with all Qi devices',
                    'supplier_price' => 1899,
                    'retail_price' => 3499,
                    'stock_quantity' => 200,
                    'weight' => 0.2,
                    'length' => 12.0,
                    'width' => 12.0,
                    'height' => 2.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['wireless-charger.jpg'],
                    'attributes' => ['power' => '15W', 'compatibility' => 'Qi Standard'],
                    'categories' => ['Electronics', 'Charging'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 1,
                ],
                [
                    'supplier_sku' => 'TGP-BT-402',
                    'supplier_product_id' => 'TGP402',
                    'name' => 'Portable Bluetooth Speaker Waterproof',
                    'description' => 'Compact waterproof Bluetooth speaker with 12-hour battery',
                    'supplier_price' => 2999,
                    'retail_price' => 5999,
                    'stock_quantity' => 150,
                    'weight' => 0.4,
                    'length' => 15.0,
                    'width' => 8.0,
                    'height' => 8.0,
                    'sync_status' => DropshipProductSyncStatuses::SYNCED,
                    'images' => ['bluetooth-speaker.jpg'],
                    'attributes' => ['waterproof' => 'IPX7', 'battery' => '12 hours'],
                    'categories' => ['Electronics', 'Audio'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 1,
                ],
                [
                    'supplier_sku' => 'TGP-SM-403',
                    'supplier_product_id' => 'TGP403',
                    'name' => 'Smart Fitness Watch',
                    'description' => 'Advanced fitness tracking watch with heart rate monitor',
                    'supplier_price' => 8999,
                    'retail_price' => 15999,
                    'stock_quantity' => 75,
                    'weight' => 0.06,
                    'length' => 5.0,
                    'width' => 4.5,
                    'height' => 1.2,
                    'sync_status' => DropshipProductSyncStatuses::PENDING_SYNC,
                    'images' => ['fitness-watch.jpg'],
                    'attributes' => ['features' => 'Heart Rate, GPS, Sleep Tracking', 'battery' => '7 days'],
                    'categories' => ['Electronics', 'Wearables', 'Fitness'],
                    'is_active' => true,
                    'minimum_order_quantity' => 1,
                    'processing_time_days' => 1,
                ],
            ],
            default => [],
        };
    }
}
